### ISSUE TITLE
Cannot run "npm install"

### ISSUE THREAD

**Issue by alcfeoh** [NeemaMwende/VisualEditor#1]
When I try to install dependencies, I get an error right way:

![image](https://github.com/user-attachments/assets/a3711b63-40a3-4d29-80d8-f6fa150cbe84)

How do you install dependencies for this project?

**Comment by NeemaMwende** [comment]
npm install should work well now, there was a dependency conflict with one of the dependencies, but everything should be okay now

**Comment by alcfeoh** [comment]
Yes, it works now
