### ISSUE TITLE
When editing a file, the correct answer does not show as checked

### ISSUE THREAD

**Issue by alcfeoh** [NeemaMwende/VisualEditor#2]
Here is an example - the checkbox should be checked for the correct answer:
![image](https://github.com/user-attachments/assets/5aec6cbb-4e35-44c9-a03c-3299beffc332)

**Comment by NeemaMwende** [comment]
Hey Alain, 
![Screenshot from 2024-12-25 18-42-36](https://github.com/user-attachments/assets/ea938d16-56c2-45e3-95c0-d2be5b35434d)
![Screenshot from 2024-12-25 18-42-20](https://github.com/user-attachments/assets/e8d3b6ad-b739-4688-a9af-76b2457add6d)
![Screenshot from 2024-12-25 18-41-45](https://github.com/user-attachments/assets/281ea575-ca4c-42f0-ad7f-2806cf47b531)
![Screenshot from 2024-12-25 18-41-34](https://github.com/user-attachments/assets/d769ab7d-e829-4576-a0a4-c35049e3c2a9)
once the user selects the correct answer from the question creation part, the correct answer should display across all files, even when editing.

**Comment by alcfeoh** [comment]
Is it something you changed since my comment? Because I edited a file and the correct answer didn't show as "checked", hence my bug report @NeemaMwende

**Comment by NeemaMwende** [comment]
Not really, I first checked before i made any changes, and it seemed okay,
does it still show on your end? Or its still a no show?

**Comment by alcfeoh** [comment]
Still doesn't when I open a folder with many files, then select a file to edit.

**Comment by NeemaMwende** [comment]
I have made some updates, please tell me if the error still persists. Also could you please share a few files in md format so i can test a few on my end and see if i missed the format

**Comment by alcfeoh** [comment]
Sure. When I open the attached file, which looks like this:
![image](https://github.com/user-attachments/assets/65d02fcb-817f-4f54-a71c-5a8f87814bd0)

Your app says the correct answer is the first one, though "Correct" is on the second answer in my markdown:
![image](https://github.com/user-attachments/assets/707e15a6-df44-40a1-ab8e-4c79905065d0)
Also, not sure why the text is all faded and barely readable. Is it because my OS is using dark mode, and it doesn't apply properly to your CSS?

[001.md](https://github.com/user-attachments/files/18255968/001.md)

**Comment by NeemaMwende** [comment]
Hey Alain

I have made a few adjustments on the markdown display, I believe everything should be okay now. On the faded display, I have tried to add adjustments to display the same across whatever OS themes present. I have however tested across different machines and the display seems okay. Kindly consider switching to light mode incase the display issue still persists(but i believe it should still display at it too). Let me know if on your end everything works okay.

**Comment by alcfeoh** [comment]
On the CSS side, just remove this from `globals.css` and then it works for me:

```
@media (prefers-color-scheme: dark) {
  :root {
    --background: #0a0a0a;
    --foreground: #ededed;
  }
}
```

**Comment by NeemaMwende** [comment]
Sure thing, was the other issue successful? The "Correct" checkbox?

**Comment by alcfeoh** [comment]
It seems to be fixed, yes

*Alain Chautard*
Google Developer Expert in Angular *
*
Consultant and trainer at angulartraining.com ( http://angulartraining.com ) - Interstate 21, LLC

***@***.***
www.interstate21.com ( http://www.interstate21.com )
Rancho Cordova, California, USA

**Comment by NeemaMwende** [comment]
Okay

**Comment by alcfeoh** [comment]
Still not working. This file does not show any answer selected.
[002.md](https://github.com/user-attachments/files/18268242/002.md)

**Comment by NeemaMwende** [comment]
I have added some strict validations to ensure all questions register atleast 1 correct answer, the files should now register and check the box.

**Comment by alcfeoh** [comment]
Ok, it seems to work fine now.
