### ISSUE TITLE
Production build fails

### ISSUE THREAD

**Issue by alcfeoh** [NeemaMwende/VisualEditor#3]
I tried to build your code for production so it could be deployed, but got the following error:
![image](https://github.com/user-attachments/assets/49e61f66-b21b-475d-9b5e-2d7fea20e162)

**Comment by NeemaMwende** [comment]
I have had several type errors for a while now preventing the build, but everything is okay now. It should be available at this link https://visual-editor-3ih8.vercel.app/

**Comment by alcfeoh** [comment]
That works.
