### ISSUE TITLE
Clicking "edit" or  "delete" doesn't do anything

### ISSUE THREAD

**Issue by alcfeoh** [NeemaMwende/VisualEditor#4]
![screenshot](https://github.com/user-attachments/assets/a4bf3496-29c2-4312-8e1c-b9563f017672)

**Comment by NeemaMwende** [comment]
Both buttons are now fixed

**Comment by alcfeoh** [comment]
I just got your latest code, and the issue is still there.

**Comment by alcfeoh** [comment]
What I do in my screenshot is still happening the same way.

**Comment by NeemaMwende** [comment]
[Uploading editor.webm…]()

**Comment by NeemaMwende** [comment]
The buttons should be okay now

**Comment by alcfeoh** [comment]
They seem to be working.
